GET http://localhost:8080/boards?size=10&page=0
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET http://localhost:8080/boards/1
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
POST http://localhost:8080/boards
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "title": "dummy title",
  "content": "dummy content"
}

###