POST http://localhost:8080/signOn
Content-Type: application/json

{
  "username": "user",
  "password": "password",
  "authorities": [
    "ROLE_USER"
  ]
}

###
POST http://localhost:8080/signIn
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
POST http://localhost:8080/signOut
Content-Type: application/json
Cookie: JSESSIONID=5A5EA5EC0F95502BF68C0E914C34610D

{}

###
DELETE http://localhost:8080/signOff
Content-Type: application/json
Cookie: JSESSIONID=646A22847951B4241BE4B87F18750FA7

{}

###
GET http://localhost:8080/public
Accept: application/json

###
GET http://localhost:8080/protected
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###
GET http://localhost:8080/protected
Accept: application/json
Cookie: JSESSIONID=572D1C57A748BD67B7012C72FEB632FB; Path=/; HttpOnly

###
GET http://localhost:8080/protected
Accept: application/json

###